name: Pull Request Plan

on:
  - pull_request

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform:
    name: Terraspace CI
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      TS_ENV: dev

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically

    - name: Install Terraspace
      run:
        .github/bin/install

# -----------------------
# ✅ TFLint Integration
# -----------------------
    - name: Cache TFLint Plugins
      uses: actions/cache@v4
      with:
        path: ~/.tflint.d/plugins
        key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - name: Setup TFLint
      uses: terraform-linters/setup-tflint@v4
      with:
        tflint_version: latest

    - name: Init TFLint
      run: tflint --init
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run TFLint
      run: tflint --chdir=app/stacks/core

# -----------------------
# ✅ Terraspace Checks
# -----------------------
    
    - name: Terraform Format Check (Lint)
      run: terraspace fmt --check --diff || true

    - name: Terraform Validate
      run: terraspace validate core

    - name: Security Scan with tfsec
      uses: aquasecurity/tfsec-action@v1.0.0

    - name: Run Checkov (Terraform Security Scan)
      uses: bridgecrewio/checkov-action@v12
      with:
        directory: app/stacks/core
        framework: terraform
        soft_fail: false       # Set to true if you want the job to continue on failure
        quiet: true        # Suppress logs unless issues are found

    - name: Terraspace Plan
      run: terraspace plan core
