# .github/workflows/test-azure-setup.yml
name: Verify Azure Setup

on:
  workflow_dispatch:

jobs:
  create-rg:
    name: Create Azure Resource Group
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Login to Azure with Federated Identity
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Create resource group
      run: |
        az group create \
          --name rg-gh-actions-test \
          --location eastus

