# .github/workflows/test-azure-setup.yml
name: Verify Azure Setup & Run Azure Login with OIDC

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/**'
jobs:
  build-and-deploy:
    name: Login to Azure
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:

    - name: Login to Azure with Federated Identity
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show
    # - name: Create resource group
    #   run: |
    #     az group create \
    #       --name rg-gh-actions-test \
    #       --location eastus

